export const alibiCases = [
  {
    id: 'san-aurelio-station',
    title: 'El ultimo tren de medianoche',
    subtitle: 'Expediente San Aurelio',
    chapterLabel: 'Estacion clausurada',
    brief: 'Un investigador privado aparece muerto durante un apagon de 17 segundos. Todos quedaron encerrados en la estacion. El Detective debe encontrar que sospechoso esta defendiendo una coartada inventada.',
    objective: 'El Detective debe acusar al sospechoso que esta defendiendo una ubicacion falsa.',
    premise:
      'Damian Robles cito a varios sospechosos en la Estacion San Aurelio para entregar una prueba antes de que el edificio reabriera al publico. Nadie debia salir hasta escuchar su acusacion.',
    howToPlay: [
      'Todos conocen el caso, el mapa y las evidencias publicas.',
      'Un jugador es Detective: no tiene coartada, dirige preguntas y emite la acusacion final.',
      'Los demas son sospechosos: cada uno recibe ubicacion, version, sonidos, detalles y una pista privada.',
      'Un sospechoso tiene una coartada falsa. Sabe donde estuvo realmente, pero debe defender la ubicacion inventada.',
      'Durante la discusion, crucen rutas, sonidos, tiempos y pistas. El Detective puede interrogar en privado y luego acusar.',
    ],
    roundPrompt:
      'El Detective no busca una confesion. Busca una ruta imposible, un sonido mal ubicado o una version que contradiga la evidencia.',
    detectiveBrief:
      'Tienes autoridad sobre la mesa. Escucha cada coartada, marca contradicciones y usa tu interrogatorio privado cuando alguien no pueda explicar su ruta.',
    detectiveTip:
      'Haz preguntas cortas: que viste, que oiste, por donde podias moverte y quien confirma tu version.',
    story: [
      '11:35 p.m. Damian Robles llega con un sobre lacrado y anuncia que tiene una fotografia que prueba quien saboteo la estacion antes del cierre.',
      '11:42 p.m. Robles camina hacia el Anden 2. La tormenta bloquea las salidas y la cabina de radio queda como unica forma de pedir ayuda.',
      '11:47 p.m. las luces se apagan durante 17 segundos. Cuando vuelven, Robles esta muerto junto al Anden 2 y la fotografia desaparecio.',
      'La puerta principal siguio cerrada. Si alguien miente, no miente para parecer inocente: miente para ocultar por donde se movio durante el apagon.',
    ],
    victim: {
      name: 'Damian Robles',
      role: 'Investigador privado',
      detail: 'Investigaba sobornos, reportes falsos y el cierre de la estacion.',
      lastSeen: '11:42 p.m., entrando al Anden 2 con un sobre lacrado.',
    },
    incident: {
      time: '11:47 p.m.',
      place: 'Anden 2',
      cause: 'Golpe durante el apagon',
    },
    map: {
      name: 'Estacion San Aurelio',
      width: 6,
      height: 4,
      crimeScene: 'Anden 2',
      zones: [
        { id: 'platform-1', name: 'Anden 1', shortName: 'Anden 1', x: 0, y: 0, w: 2, h: 1, type: 'platform', note: 'Bancos mojados, vias vacias y vista parcial hacia el Anden 2.' },
        { id: 'platform-2', name: 'Anden 2', shortName: 'Anden 2', x: 2, y: 0, w: 2, h: 1, type: 'crime', note: 'Escena del crimen. La victima aparecio junto al borde de la via.' },
        { id: 'radio', name: 'Cabina de radio', shortName: 'Radio', x: 4, y: 0, w: 2, h: 1, type: 'control', note: 'El microfono quedo abierto y grabo respiracion antes del golpe.' },
        { id: 'ticket-office', name: 'Taquilla', shortName: 'Taquilla', x: 0, y: 1, w: 1, h: 1, type: 'public', note: 'La ventanilla mira hacia la sala de espera, no hacia los andenes.' },
        { id: 'waiting-room', name: 'Sala de espera', shortName: 'Espera', x: 1, y: 1, w: 2, h: 1, type: 'public', note: 'Desde los bancos se ve una sombra cruzar hacia el Anden 2.' },
        { id: 'cafeteria', name: 'Cafeteria cerrada', shortName: 'Cafe', x: 3, y: 1, w: 1, h: 1, type: 'service', note: 'La puerta fue forzada desde dentro y aun huele a cafe viejo.' },
        { id: 'luggage', name: 'Bodega de equipaje', shortName: 'Bodega', x: 4, y: 1, w: 2, h: 1, type: 'service', note: 'Huellas humedas salen de aqui hacia el pasillo interno.' },
        { id: 'maintenance', name: 'Pasillo de mantenimiento', shortName: 'Pasillo', x: 0, y: 2, w: 2, h: 1, type: 'route', note: 'Ruta oculta entre bodega, archivo y andenes. Sirve para moverse sin pasar por recepcion.' },
        { id: 'office', name: 'Oficina del jefe', shortName: 'Oficina', x: 2, y: 2, w: 2, h: 1, type: 'control', note: 'El reloj de pared se detuvo a la misma hora que el reloj principal.' },
        { id: 'restrooms', name: 'Banos', shortName: 'Banos', x: 4, y: 2, w: 1, h: 1, type: 'public', note: 'El lavamanos quedo abierto y el suelo tiene polvo de archivo.' },
        { id: 'exit-hall', name: 'Vestibulo principal', shortName: 'Vestibulo', x: 5, y: 2, w: 1, h: 2, type: 'public', note: 'Puertas cerradas por seguridad. Nadie pudo abandonar el edificio.' },
        { id: 'archive', name: 'Archivo de rutas', shortName: 'Archivo', x: 0, y: 3, w: 2, h: 1, type: 'service', note: 'Mapas antiguos muestran accesos internos hacia el pasillo de mantenimiento.' },
        { id: 'electrical', name: 'Cuarto electrico', shortName: 'Electricidad', x: 2, y: 3, w: 2, h: 1, type: 'control', note: 'La caja de fusibles fue manipulada minutos antes del apagon.' },
        { id: 'locker', name: 'Casilleros', shortName: 'Casilleros', x: 4, y: 3, w: 1, h: 1, type: 'service', note: 'Un casillero conserva olor a lluvia y papel quemado.' },
      ],
      routes: [
        ['platform-1', 'platform-2'],
        ['platform-2', 'waiting-room'],
        ['platform-2', 'radio'],
        ['waiting-room', 'ticket-office'],
        ['waiting-room', 'cafeteria'],
        ['cafeteria', 'luggage'],
        ['luggage', 'maintenance'],
        ['maintenance', 'platform-1'],
        ['maintenance', 'archive'],
        ['maintenance', 'office'],
        ['office', 'electrical'],
        ['office', 'restrooms'],
        ['restrooms', 'exit-hall'],
        ['restrooms', 'locker'],
        ['locker', 'exit-hall'],
      ],
    },
    publicEvidence: [
      'El apagon duro solo 17 segundos: nadie pudo hacer una ruta larga sin quedar expuesto.',
      'La fotografia del sobre desaparecio; el sobre vacio quedo junto al cuerpo.',
      'Huellas humedas conectan la Bodega de equipaje con el Pasillo de mantenimiento.',
      'La radio grabo respiracion, un golpe y una campana de anden antes de cortarse.',
    ],
    tableQuestions: [
      'Que podias ver desde tu ubicacion?',
      'Que sonido escuchaste durante el apagon?',
      'Por que elegiste moverte o quedarte quieto?',
      'Quien podia cruzar hacia el Anden 2 mas rapido?',
    ],
    locations: [
      'Anden 1',
      'Anden 2',
      'Cabina de radio',
      'Taquilla',
      'Sala de espera',
      'Cafeteria cerrada',
      'Bodega de equipaje',
      'Pasillo de mantenimiento',
      'Oficina del jefe',
      'Banos',
      'Vestibulo principal',
      'Archivo de rutas',
      'Cuarto electrico',
      'Casilleros',
    ],
    statements: {
      'Anden 1': 'Revisaba los bancos mojados cuando el reloj se detuvo y escuche una campana del otro anden.',
      'Anden 2': 'Segui un golpe metalico cerca de las vias y me quede inmovil cuando se apagaron las luces.',
      'Cabina de radio': 'Intentaba pedir ayuda por radio; alcance a oir respiracion antes de que la senal muriera.',
      Taquilla: 'Contaba monedas bajo la ventanilla y solo vi sombras cruzar por la sala de espera.',
      'Sala de espera': 'Me quede junto a los bancos. Vi una sombra moverse hacia el Anden 2 durante el apagon.',
      'Cafeteria cerrada': 'Buscaba agua y encontre la puerta mal cerrada antes de escuchar el golpe.',
      'Bodega de equipaje': 'Movia maletas viejas por las goteras. El suelo estaba mojado antes del apagon.',
      'Pasillo de mantenimiento': 'Segui un ruido por el pasillo interno, pero no llegue hasta los andenes.',
      'Oficina del jefe': 'Buscaba el libro de guardia para confirmar quien habia entrado a la estacion.',
      Banos: 'Fui a lavarme las manos porque tenia polvo de los archivos y el lavamanos se quedo abierto.',
      'Vestibulo principal': 'Vigilaba las puertas principales. Si alguien salio, no fue por ahi.',
      'Archivo de rutas': 'Revisaba mapas antiguos para entender los accesos internos y los pasillos cerrados.',
      'Cuarto electrico': 'Fui a revisar los fusibles despues de notar parpadeos en las luces.',
      Casilleros: 'Buscaba una chaqueta seca; mi abrigo estaba empapado por la lluvia.',
    },
    versions: {
      'Anden 1': {
        statement: 'Revisaba los bancos mojados cuando el reloj se detuvo.',
        saw: 'Una sombra cruzo cerca del Anden 2, pero la lluvia contra los vidrios impidio ver su cara.',
        heard: 'Una campana corta sono antes del golpe.',
        detail: 'Desde alli se distingue el borde del Anden 2, pero no la Cabina de radio.',
        risk: 'Si dice que vio la Taquilla, esta exagerando: desde Anden 1 no hay linea directa.',
      },
      'Anden 2': {
        statement: 'Segui un golpe metalico cerca de las vias y me quede inmovil cuando se apagaron las luces.',
        saw: 'El sobre cayo al suelo antes de que todo quedara oscuro.',
        heard: 'El golpe fue seco y muy cercano.',
        detail: 'Es la zona mas peligrosa de declarar porque es la escena del crimen.',
        risk: 'Debe explicar por que no vio a Damian si estaba tan cerca.',
      },
      'Cabina de radio': {
        statement: 'Intentaba pedir ayuda por radio cuando la senal se corto.',
        saw: 'La luz roja del microfono quedo encendida durante el apagon.',
        heard: 'Respiracion, golpe y campana quedaron grabados en ese orden.',
        detail: 'Desde la cabina se oye mejor el Anden 2 que el Vestibulo.',
        risk: 'Si cambia el orden de los sonidos, la evidencia de la radio lo contradice.',
      },
      Taquilla: {
        statement: 'Contaba monedas bajo la ventanilla mientras esperaba instrucciones.',
        saw: 'Solo se ven sombras de la Sala de espera, no el Anden 2 completo.',
        heard: 'La campana sono apagada, como si viniera desde lejos.',
        detail: 'La ventanilla tiene vista limitada hacia el centro de la estacion.',
        risk: 'No puede afirmar haber visto el golpe ni la Cabina de radio.',
      },
      'Sala de espera': {
        statement: 'Me quede junto a los bancos porque la tormenta bloqueo la salida.',
        saw: 'Una silueta se movio hacia el Anden 2 durante el apagon.',
        heard: 'Primero una campana, despues un golpe.',
        detail: 'Esta zona conecta visualmente con andenes y taquilla.',
        risk: 'Si dice que no vio nada, contradice la visibilidad parcial de la sala.',
      },
      'Cafeteria cerrada': {
        statement: 'Buscaba agua y encontre la puerta de la cafeteria mal cerrada.',
        saw: 'La puerta hacia Bodega estaba entreabierta.',
        heard: 'Un sonido de cajas se mezclo con el golpe.',
        detail: 'Puede conectar con Bodega, pero no con Anden 2 sin pasar por otra zona.',
        risk: 'Una ruta directa al Anden 2 desde aqui suena falsa.',
      },
      'Bodega de equipaje': {
        statement: 'Movia maletas viejas por las goteras del techo.',
        saw: 'Huellas humedas iban hacia el pasillo interno.',
        heard: 'Cajas arrastradas y luego la campana del anden.',
        detail: 'La bodega conecta con el Pasillo de mantenimiento.',
        risk: 'Debe explicar por que habia agua en el suelo y si toco las maletas.',
      },
      'Pasillo de mantenimiento': {
        statement: 'Segui un ruido por el pasillo interno, pero no llegue a los andenes.',
        saw: 'Una luz parpadeaba hacia el Archivo de rutas.',
        heard: 'El golpe se oyo amortiguado, como detras de una pared.',
        detail: 'Es una ruta oculta que conecta varias zonas sin pasar por recepcion.',
        risk: 'Es sospechoso porque permite moverse rapido sin que la mesa lo vea.',
      },
      'Oficina del jefe': {
        statement: 'Buscaba el libro de guardia para confirmar quien habia entrado.',
        saw: 'El reloj de pared se detuvo exactamente a las 11:47.',
        heard: 'El zumbido electrico bajo justo antes del apagon.',
        detail: 'La oficina esta cerca del Cuarto electrico.',
        risk: 'Si ignora el reloj o los fusibles, pierde credibilidad.',
      },
      Banos: {
        statement: 'Fui a lavarme las manos porque tenia polvo de los archivos.',
        saw: 'El lavamanos siguio abierto cuando regreso la luz.',
        heard: 'Agua corriendo y un golpe lejano.',
        detail: 'Desde los banos no se ve el Anden 2.',
        risk: 'No puede dar detalles visuales de andenes ni radio.',
      },
      'Vestibulo principal': {
        statement: 'Vigilaba las puertas principales para asegurar que nadie saliera.',
        saw: 'Las puertas siguieron cerradas durante todo el apagon.',
        heard: 'La campana sono lejos y el golpe casi no se distinguio.',
        detail: 'Sirve para confirmar que nadie abandono la estacion.',
        risk: 'No puede hablar de movimientos internos con precision.',
      },
      'Archivo de rutas': {
        statement: 'Revisaba mapas antiguos para entender los accesos internos.',
        saw: 'Un plano marcaba el Pasillo de mantenimiento como ruta de servicio.',
        heard: 'Papeles cayendo, luego un golpe amortiguado.',
        detail: 'Puede explicar la existencia de rutas ocultas.',
        risk: 'Si niega conocer el pasillo, contradice lo que habia en los mapas.',
      },
      'Cuarto electrico': {
        statement: 'Fui a revisar los fusibles despues de notar parpadeos.',
        saw: 'La caja tenia una palanca manipulada antes del apagon.',
        heard: 'Un chasquido electrico ocurrio antes del silencio.',
        detail: 'Esta zona explica el apagon, pero no la fotografia desaparecida.',
        risk: 'Debe explicar por que no aviso a la mesa del problema electrico.',
      },
      Casilleros: {
        statement: 'Buscaba una chaqueta seca porque la mia estaba empapada.',
        saw: 'Un casillero tenia papel quemado y olor a lluvia.',
        heard: 'La campana sono lejos; despues alguien corrio por el pasillo.',
        detail: 'Esta cerca de banos y vestibulo, no de los andenes.',
        risk: 'Si se adjudica sonidos muy claros del Anden 2, puede estar mintiendo.',
      },
    },
    clues: [
      'Si alguien dice estar en {liarClaim}, preguntale que podia ver. Esa zona no explica bien el movimiento hacia el Anden 2.',
      'Las huellas humedas importan: quien hable de Bodega, Pasillo o Archivo debe explicar por que habia agua en el suelo.',
      'El apagon fue muy corto. Desconfia de una version que incluya caminar por media estacion.',
      'Cruza tu version con {otherName}. Si sus sonidos no coinciden, alguien esta acomodando el orden.',
      'La campana de anden se oye mejor desde las zonas cercanas a los andenes o la radio.',
    ],
    liarHints: [
      'Tu coartada falsa es {liarClaim}. Mantenla simple: estabas alli, oiste el apagon y no viste la cara de nadie.',
      'No expliques rutas largas. Si te presionan, di que la tormenta y la oscuridad confundieron los sonidos.',
      'No menciones la fotografia faltante antes de que otro jugador la saque a la mesa.',
      '{otherName} puede tener una pista incomoda. Haz que parezca que confundio el sonido de la radio con la campana.',
    ],
  },
]
