// Mismo banco que el cliente — fuente de verdad en el servidor

export const categories = {
  animales:    { label: 'Animales' },
  comida:      { label: 'Comida' },
  lugares:     { label: 'Lugares' },
  objetos:     { label: 'Objetos' },
  peliculas:   { label: 'Películas' },
  deportes:    { label: 'Deportes' },
  profesiones: { label: 'Profesiones' },
  emociones:   { label: 'Emociones' },
  naturaleza:  { label: 'Naturaleza' },
  tecnologia:  { label: 'Tecnología' },
  historia:    { label: 'Historia' },
  misterio:    { label: 'Misterio' },
  colombia:    { label: 'Colombia' },
  musica:      { label: 'Música' },
  literatura:  { label: 'Literatura' },
  videojuegos: { label: 'Videojuegos' },
  seriesTv:    { label: 'Series TV' },
  mitologia:   { label: 'Mitología' },
  cocteles:    { label: 'Cócteles' },
  marcas:      { label: 'Marcas' },
  arte:        { label: 'Arte' },
  arquitectura:{ label: 'Arquitectura' },
  geografia:   { label: 'Geografía' },
  astronomia:  { label: 'Astronomía' },
  gastronomiaColombiana: { label: 'Gastronomía colombiana' },
}

export const wordBank = {
  animales: ['Elefante','Delfín','Cóndor','Tarántula','Mantarraya','Guepardo','Pingüino','Orca','Camaleón','Pulpo','Murciélago','Koala','Tiburón','Jaguar','Búho','Erizo','Llama','Capibara','Ornitorrinco','Hipopótamo','Mariposa','Cocodrilo','Caballo','Ardilla','Lobo','Águila','Tortuga','Mapache','Foca','Avestruz'],
  comida: ['Sushi','Arepa','Ceviche','Fondue','Ramen','Empanada','Pizza','Lasaña','Tacos','Paella','Hamburguesa','Croissant','Bandeja Paisa','Sancocho','Hummus','Risotto','Falafel','Tamales','Curry','Cazuela','Tartar','Morcilla','Ajiaco','Kebab','Quesadilla','Crepe','Bagel','Pretzel','Ñoquis','Carbonara'],
  lugares: ['Playa','Volcán','Aeropuerto','Mercado','Catedral','Faro','Desierto','Selva','Cementerio','Castillo','Hospital','Universidad','Biblioteca','Estadio','Museo','Pirámide','Glaciar','Cascada','Pantano','Cueva','Manicomio','Subway','Penthouse','Cabaña','Iglú','Monasterio','Observatorio','Astillero','Pozo','Mausoleo'],
  objetos: ['Telescopio','Brújula','Candado','Reloj de Arena','Pergamino','Lupa','Daga','Linterna','Espejo','Bastón','Martillo','Antifaz','Trofeo','Sello','Ancla','Vela','Llave','Mochila','Gafas','Pulsera','Navaja','Yunque','Termómetro','Caleidoscopio','Ábaco','Caja Fuerte','Trípode','Bolígrafo','Caja Musical','Calabozo'],
  peliculas: ['Titanic','Matrix','Coco','El Padrino','Parasite','Avatar','Interestelar','Inception','Joker','Gladiador','Forrest Gump','Up','Frozen','Ratatouille','Toy Story','Shrek','Pulp Fiction','Star Wars','Harry Potter','Pirates del Caribe','El Rey León','Bambi','Bohemian Rhapsody','La La Land','Memento','Whiplash','Amélie','Cisne Negro','Dunkerque','Drive'],
  deportes: ['Surf','Esgrima','Polo','Escalada','Waterpolo','Lucha Libre','Béisbol','Tenis','Boxeo','Sumo','Karate','Patinaje','Esquí','Jiu-jitsu','Bádminton','Hípica','Rugby','Softbol','Pesca','Triatlón','Voleibol','Golf','Snowboard','Ciclismo','Atletismo','Buceo','Yoga','Parkour','Tiro con Arco','Tenis de Mesa'],
  profesiones: ['Forense','Sommelier','Arqueólogo','Locutor','Taxidermista','Cirujano','Astronauta','Bombero','Carpintero','Veterinario','Detective','Notario','Periodista','Tatuador','Bibliotecario','Mecánico','Joyero','Cartero','Diseñador','Soplador de Vidrio','Relojero','Pirotécnico','Bailarín','Geólogo','Marinero','Domador','Comediante','Cazatalentos','Ilusionista','Soldador'],
  emociones: ['Nostalgia','Euforia','Celos','Asombro','Melancolía','Rabia','Vergüenza','Orgullo','Ansiedad','Calma','Esperanza','Compasión','Envidia','Aburrimiento','Curiosidad','Pánico','Cariño','Decepción','Frustración','Ternura','Resentimiento','Alegría','Tristeza','Confianza','Inseguridad','Alivio','Asco','Gratitud','Desprecio','Fascinación'],
  naturaleza: ['Aurora Boreal','Tornado','Géiser','Manglar','Corriente Marina','Tsunami','Arcoíris','Selva','Iceberg','Coral','Tundra','Acantilado','Meteoro','Pantano','Constelación','Atolón','Sabana','Estepa','Eclipse','Helada','Niebla','Tormenta','Marea','Brisa','Volcán','Estalactita','Duna','Bahía','Quebrada','Fiordo'],
  tecnologia: ['Algoritmo','Firewall','Dron','Satélite','Aplicación','Servidor','Holograma','Robot','Microchip','Inteligencia Artificial','Pixel','Bluetooth','Criptomoneda','Realidad Virtual','Streaming','Antivirus','Router','Red Social','Código QR','Impresora 3D','Procesador','Cookie','Monitor','Pantalla Táctil','GPS','Nube','Memoria USB','Fibra Óptica','5G','Captcha'],
  historia: ['Gladiador','Faraón','Samurái','Vikingo','Alquimista','Conquistador','Cortesano','Caballero','Pirata','Cruzado','Mosquetero','Reina','Bárbaro','Romano','Inquisidor','Profeta','Cazador','Bufón','Espadachín','Guerrero','Centurión','Herrero','Senador','Druida','Cartógrafo','Astrónomo','Embajador','Inventor','Cardenal','Esclavo'],
  misterio: ['Fantasma','Conspiración','Espía','Código Morse','Tótem','Tarot','Tablero Ouija','Maldición','Profecía','Ritual','Reliquia','Ovni','Hechizo','Vampiro','Hombre Lobo','Sacrificio','Cripta','Catacumba','Médium','Exorcista','Bruja','Premonición','Telepatía','Levitación','Reencarnación','Talismán','Pacto','Triángulo de las Bermudas','Profanación','Conjuro'],
  colombia: ['Café','Vallenato','Esmeralda','Cumbia','Wayuu','Chiva','Sancocho','Arepa','Aguardiente','Bandeja Paisa','Tejo','Caldas','Cartagena','Medellín','Cocora','Tayrona','Macondo','Mochila','Bambuco','Lechona','Buñuelo','Sombrero Vueltiao','Mondongo','Chicha','Frailejón','Pacífico','Páramo','Río Magdalena','Boyacá','Arequipe'],
  musica: ['Guitarra','Piano','Violín','Batería','Saxofón','Trompeta','Flauta','Arpa','Tambor','Maracas','Acordeón','Melodía','Ritmo','Coro','Orquesta','Banda','Solista','Concierto','Festival','Karaoke','Salsa','Merengue','Reguetón','Rock','Pop','Jazz','Cumbia','Vallenato','Bambuco','Himno'],
  literatura: ['Novela','Cuento','Poema','Fábula','Leyenda','Mito','Crónica','Ensayo','Biblioteca','Librería','Autor','Lector','Narrador','Personaje','Capítulo','Prólogo','Epílogo','Portada','Marcador','Diccionario','Enciclopedia','Cómic','Manga','Teatro','Obra','Diario','Carta','Biografía','Aventuras','Fantasía'],
  videojuegos: ['Mario','Zelda','Minecraft','Tetris','Pac-Man','Sonic','Kirby','Pikachu','Donkey Kong','Animal Crossing','Splatoon','Rocket League','Stardew Valley','Fall Guys','Rayman','Crash Bandicoot','Spyro','Just Dance','Portal','SimCity','The Sims','Overcooked','Celeste','Hollow Knight','Cuphead','Among Us','FIFA','Gran Turismo','Forza','LittleBigPlanet'],
  seriesTv: ['Avatar','Bob Esponja','Los Simpson','Friends','Dragon Ball','Pokémon','Phineas y Ferb','Gravity Falls','Steven Universe','Hora de Aventura','El Chavo','Heidi','Scooby-Doo','Los Picapiedra','Los Supersónicos','Doraemon','Naruto','One Piece','Sailor Moon','Ben 10','Kim Possible','Malcolm','Full House','The Mandalorian','Doctor Who','Smallville','iCarly','Victorious','El Príncipe del Rap','Cobra Kai'],
  mitologia: ['Zeus','Hera','Atenea','Apolo','Artemisa','Hermes','Poseidón','Hades','Afrodita','Ares','Hércules','Perseo','Medusa','Pegaso','Centauro','Minotauro','Odiseo','Aquiles','Thor','Odín','Loki','Freya','Valquiria','Anubis','Osiris','Isis','Ra','Horus','Quetzalcóatl','Inti'],
  cocteles: ['Coctel de frutas','Limonada de coco','Piña colada sin alcohol','Mojito sin alcohol','Sangría sin alcohol','Mocktail tropical','Granizado de mango','Batido de fresa','Smoothie de banano','Agua de panela con limón','Refajo sin alcohol','Naranjada','Limonada de hierbabuena','Lulada','Champús','Malteada de vainilla','Malteada de chocolate','Cerezada','Mandarinada','Té helado','Ponche de frutas','Agua fresca','Horchata','Jugo verde','Jugo de guanábana','Jugo de maracuyá','Jugo de mora','Jugo de lulo','Soda italiana','Coctel de sandía'],
  marcas: ['LEGO','Nintendo','PlayStation','Xbox','Disney','Pixar','Marvel','Nike','Adidas','Puma','Apple','Samsung','Google','Microsoft','Netflix','YouTube','Spotify','Coca-Cola','Pepsi','McDonald’s','Burger King','Starbucks','Amazon','IKEA','Toyota','Honda','Ford','Nissan','Colsubsidio','Éxito'],
  arte: ['Acuarela','Óleo','Escultura','Mural','Retrato','Paisaje','Bodegón','Collage','Grabado','Cerámica','Fotografía','Ilustración','Dibujo','Carboncillo','Pastel','Grafiti','Mosaico','Tapiz','Origami','Caligrafía','Abstracto','Cubismo','Surrealismo','Impresionismo','Realismo','Renacimiento','Barroco','Museo','Galería','Lienzo'],
  arquitectura: ['Arco','Columna','Cúpula','Fachada','Balcón','Patio','Atrio','Torre','Puente','Acueducto','Anfiteatro','Templo','Rascacielos','Catedral','Pagoda','Palacio','Villa','Teatro','Biblioteca','Estación','Plaza','Jardín','Muralla','Fortaleza','Azotea','Terraza','Vestíbulo','Escalera','Ventanal','Corredor'],
  geografia: ['Continente','Océano','Montaña','Cordillera','Valle','Meseta','Llanura','Isla','Península','Archipiélago','Golfo','Bahía','Río','Lago','Laguna','Delta','Cañón','Desierto','Selva','Sabana','Tundra','Glaciar','Volcán','Catarata','Mapa','Brújula','Ecuador','Meridiano','Latitud','Longitud'],
  astronomia: ['Sol','Luna','Mercurio','Venus','Tierra','Marte','Júpiter','Saturno','Urano','Neptuno','Plutón','Asteroide','Cometa','Meteorito','Galaxia','Nebulosa','Supernova','Constelación','Orión','Vía Láctea','Telescopio','Observatorio','Eclipse','Marea','Órbita','Cohete','Satélite','Astronauta','Estrella Fugaz','Agujero Negro'],
  gastronomiaColombiana: ['Ajiaco','Bandeja Paisa','Sancocho','Arepa de huevo','Arepa boyacense','Lechona','Tamal','Empanada','Pandebono','Buñuelo','Almojábana','Changua','Mute','Mondongo','Sobrebarriga','Fritanga','Patacón','Hogao','Aborrajado','Cazuela de mariscos','Mote de queso','Arroz con coco','Cabrito','Mamona','Hormigas culonas','Oblea','Natilla','Manjar blanco','Merengón','Cholado'],
}

export const relatedWords = {
  Playa: ['Costa', 'Lago', 'Río', 'Piscina', 'Delta', 'Bahía', 'Laguna', 'Estanque'],
  Volcán: ['Montaña', 'Cráter', 'Géiser', 'Caverna', 'Acantilado'],
  Desierto: ['Sabana', 'Estepa', 'Duna', 'Llanura'],
  Selva: ['Bosque', 'Jungla', 'Manglar', 'Pantano'],
  Castillo: ['Palacio', 'Fortaleza', 'Mansión', 'Torre'],
  Elefante: ['Rinoceronte', 'Hipopótamo', 'Búfalo', 'Mamut'],
  Delfín: ['Tiburón', 'Ballena', 'Orca', 'Foca'],
  Águila: ['Halcón', 'Cóndor', 'Buitre', 'Búho'],
  Sushi: ['Sashimi', 'Ramen', 'Tempura', 'Maki'],
  Pizza: ['Lasaña', 'Calzone', 'Focaccia', 'Bruschetta'],
  Tacos: ['Burrito', 'Quesadilla', 'Enchilada', 'Tostada'],
  Hamburguesa: ['Sándwich', 'Hot Dog', 'Wrap', 'Bocadillo'],
  Forense: ['Detective', 'Médico', 'Patólogo', 'Cirujano'],
  Astronauta: ['Piloto', 'Aviador', 'Cosmonauta', 'Capitán'],
  Bombero: ['Paramédico', 'Policía', 'Socorrista', 'Rescatista'],
  Dron: ['Satélite', 'Helicóptero', 'Avión', 'Misil'],
  Robot: ['Androide', 'Cyborg', 'Autómata', 'Drone'],
  Tornado: ['Huracán', 'Tifón', 'Ciclón', 'Tormenta'],
  Iceberg: ['Glaciar', 'Témpano', 'Polo', 'Banco de Hielo'],
}
